### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ReaperXYZ** [ianzhou01/BeesEyeView#4]
Report issues
Report here - https://docs.google.com/document/d/1lnT0mLVWc0pA7cKGvXnYMjDJJSswipS_Cl4gXmBu8EY/edit?usp=sharing
- [x] Write the Deliverable
    - [x] Introduction
        - [x] Team Name
        - [x] Team Members + Github names
        - [x] Link to Github Repo
        - [x] Link to Video demo
    - [x] Refined Proposal 
        - [x] Problem statment
        - [x] Motivation
        - [x] Implemented Features
        - [x] Description of the Data
        - [x] Tools/Languages/APIs/Libraries used
        - [x] Algorithms Implemented
        - [x] Additional Data Structures/Algorithms used
        - [x] Role distribution
    - [x] Analysis
        - [x] Changes made after proposal and rationale
        - [x] Big O worst case complexity of the major functions and features implemented
    - [x] Reflection
        - [x] Overall Experience
        - [x] Challenges
        - [x] Changes if we started again
        - [x] What each member learned
    - [x] References
- [x] Create a video of project
- [x] Make document pretty/formatted

Programming issues
- [x] Sort out the sorting algorithms
    - [x] Timsort
    - [x] Introsort 
- [x] Implement full json data
- [x] Apply sorting algorithms to json data
- [x] Create filter for user input
- [x] Take in user input
- [x] Finalize main.cpp to integrate all of the above
- [x] Create UI
- [x] Integrate program with UI
- [x] Beautify UI (optional)
- [x] Make sure we have a good amount of comments explaining things
- [x] Make sure code is well organized

Other Stuff (NEEDS TO BE DONE SAME DAY AS MAIN THING IS DUE):
- [x] Group feedback
- [x] Peer feedback
